- name: "Web server setup"
  hosts: localhost
  become: true
  gather_facts: false
  vars: 
    packages:
     - git
     - curl
     - vim
    
    users:
     - devops
     - ansible

  tasks:
    - name: Install git
      ansible.builtin.package:
         name: "{{ item }}"
         state: present
      loop: "{{ packages }}"
 
    - name: Create user
      ansible.builtin.user:
          name: "{{ item }}"
          state: present
      loop: "{{ users }}"

    - name: Start service
      ansible.builtin.service:
          name: sshd
          state: started

    - name: Start httpd service
      ansible.builtin.service:
          name: httpd
          state: started